# Generated by Django 6.0.3 on 2026-03-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True)),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('avg_speed_kph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], db_index=True, default='low', max_length=20)),
                ('occupancy_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_records', to='cameras.camera')),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['camera', '-measured_at'], name='traffic_tra_camera__12113c_idx')],
            },
        ),
    ]
