# Generated by Django 6.0.3 on 2026-03-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_for', models.DateTimeField(db_index=True)),
                ('horizon_minutes', models.PositiveIntegerField(default=5)),
                ('predicted_congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_vehicle_count', models.PositiveIntegerField()),
                ('predicted_avg_speed_kph', models.DecimalField(decimal_places=2, max_digits=6)),
                ('predicted_occupancy_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transition_probabilities', models.JSONField(blank=True, default=dict)),
                ('based_on_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_predictions', to='traffic.traffic')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='cameras.camera')),
            ],
            options={
                'ordering': ['-predicted_for', '-generated_at'],
                'indexes': [models.Index(fields=['camera', '-predicted_for'], name='traffic_tra_camera__a1430c_idx')],
            },
        ),
    ]
