# Generated by Django 6.0.3 on 2026-03-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('traffic', '0002_trafficprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.BigIntegerField(db_index=True, unique=True)),
                ('measured_at', models.DateTimeField(db_index=True)),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('avg_speed_kph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], db_index=True, max_length=20)),
                ('occupancy_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
                ('original_updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='traffic',
            index=models.Index(fields=['-measured_at'], name='traffic_tra_measure_f615a2_idx'),
        ),
        migrations.AddIndex(
            model_name='traffic',
            index=models.Index(fields=['camera', 'congestion_level', '-measured_at'], name='traffic_tra_camera__1003cd_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficprediction',
            index=models.Index(fields=['-generated_at'], name='traffic_tra_generat_4dd174_idx'),
        ),
        migrations.AddField(
            model_name='trafficarchive',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera'),
        ),
        migrations.AddIndex(
            model_name='trafficarchive',
            index=models.Index(fields=['camera', '-measured_at'], name='traffic_tra_camera__b37001_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficarchive',
            index=models.Index(fields=['-archived_at'], name='traffic_tra_archive_9abfc0_idx'),
        ),
    ]
