# Generated by Django 6.0.3 on 2026-03-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('motorbike', 'Motorbike'), ('emergency', 'Emergency'), ('other', 'Other')], db_index=True, max_length=20)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lane_number', models.PositiveSmallIntegerField(default=1)),
                ('is_violation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_events', to='cameras.camera')),
                ('traffic_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_events', to='traffic.traffic')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['camera', '-detected_at'], name='vehicles_ve_camera__98d068_idx')],
            },
        ),
    ]
